---
- hosts: minecraft
  vars:
    server_url: "https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar"
    ebs_device: "/dev/xvdb"
    ebs_fstype: "ext4"
    ebs_mount_point: "/mnt/server"
    server_install_path: "{{ ebs_mount_point }}/minecraft"
    server_install_filename: "minecraft_server.jar"
    init_script: "/etc/init.d/minecraft"
  sudo: yes
  tasks:
    - name: Format EBS volume
      filesystem: dev="{{ ebs_device }}" fstype={{ ebs_fstype }}

    - name: Mount ebs volume
      mount: fstype={{ ebs_fstype }} name="{{ ebs_mount_point }}" src="{{ ebs_device }}" state=mounted

    - name: Install JRE 7
      apt: name=openjdk-7-jre state=installed update_cache=true

    - name: Create server install directory
      file: path="{{ server_install_path }}" state=directory

    - name: Download Minecraft server
      get_url: dest="{{ server_install_path }}/{{ server_install_filename }}" url="{{ server_url }}"

    - name: Install configuration files
      copy: src="files/config/" dest="{{ server_install_path }}"

    - name: Install start script
      copy: src="files/scripts" dest="{{ server_install_path }}" mode=0755

    - name: Install init script
      copy: src="files/init.d/minecraft" dest="{{ init_script }}" mode=0755

    - name: Stop minecraft service
      service: name=minecraft state=stopped

    - name: Set minecraft service to start on boot
      service: name=minecraft enabled=yes

    - name: Start minecraft service
      service: name=minecraft state=started
      
